[package]
name = "halo2-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ff = "0.13.0"
halo2_proofs = { git = "https://github.com/zcash/halo2.git", rev = "2c2d449af09798abb80a143cd6b2eaef55ff67ea" }
pasta_curves = "0.5"
rand_core = { version = "0.6", features = [ "getrandom" ] }
